In [26]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [2]:
df1 = pd.read_csv('BLM1.csv')

In [3]:
df2 = pd.read_csv('BLM2.csv')

In [4]:
df3 = pd.read_csv('BLM3.csv')

In [8]:
df1['week'] = '1'
df1['class'] = 0
#origin_index = df1.index.tolist()
#df1 = df1.append(df1, ignore_index=True)

In [9]:
df2['week'] = '2'
df2['class'] = 0

In [10]:
df3['week'] = '3'
df3['class'] = 0

In [11]:
def classification(x):
    for i in range(len(x)):
        if x['retweet_count'][i]==0:
            x.loc[i, ('class')]=0
        elif x['retweet_count'][i]<100:
            x.loc[i, ('class')]=1
        elif x['retweet_count'][i]<1000:
            x.loc[i, ('class')]=2
        elif x['retweet_count'][i]>=1000:
            x.loc[i, ('class')]=3
    return(x)

In [12]:
df1=classification(df1)
df2=classification(df2)
df3=classification(df3)

In [13]:
test=df3[['retweet_count','class']]

In [14]:
test.head(500)

     retweet_count  class
0              709      2
1                2      1
2                0      0
3                0      0
4                0      0
..             ...    ...
495              3      1
496              2      1
497              2      1
498              0      0
499              0      0

[500 rows x 2 columns]

In [15]:
df = df1.append([df2,df3])

In [16]:
for col in df.columns:
    print(col)

id
tweetid
guid
link
author
title
description
pubdate
source
favorite_count
retweet_count
lang
quoted_text
tweet_type
in_reply_to_screen_name
in_reply_to_user_id
in_reply_to_status_id
retweeted_screen_name
retweeted_user_id
retweeted_status_id
user_id
profile_image_url
user_statuses_count
user_friends_count
user_followers_count
user_created_at
user_bio
user_location
user_verified
Unnamed: 29
week
class

In [17]:
df['user_created_at'] = pd.to_datetime(df['user_created_at'],format='%Y%m%d %H:%M:%S')

In [18]:
df.head()

,id,tweetid,guid,link,author,title,description,pubdate,source,favorite_count,...,user_statuses_count,user_friends_count,user_followers_count,user_created_at,user_bio,user_location,user_verified,Unnamed: 29,week,class
0,1,1401948148004687873,https://twitter.com/Lynn_GT/statuses/1401948148004687873,https://twitter.com/Lynn_GT/statuses/1401948148004687873,Lynn_GT,It’s going to be interesting to hear all those sports fans saying you shouldn’t bring politics into football (BLM - not that I think it’s political) squaring their approval of Johnson wading in on the cricket and Olly Robinson.,It’s going to be interesting to hear all those sports fans saying you shouldn’t bring politics into football (BLM - not that I think it’s political) squaring their approval of Johnson wading in on the cricket and Olly Robinson.,2021-06-07 13:04:20,Twitter for iPhone,3,...,51125,439,6839,2010-05-17 16:38:35,"Lover of Entlebuchers, Italy and Amarone in equal parts! I no longer follow back automatically. #WokeAndProud",NaN,NaN,NaN,1,0
1,2,1401947685964468230,https://twitter.com/ilyasahShabazz/statuses/1401947685964468230,https://twitter.com/ilyasahShabazz/statuses/1401947685964468230,ilyasahShabazz,"Looking forward to sharing my thoughts with this dynamic duo, on the Black Family panel, at #BeyondtheBuzzwords tomorrow, Tuesday and Wednesday, June 8th and June 9th! Don’t miss it: https://t.co/B1JRaP4ZkE @apbspeakers @NdabaMandela @TutuNaomi #BLM #DEI https://t.co/OLT5XgzUxa","Looking forward to sharing my thoughts with this dynamic duo, on the Black Family panel, at #BeyondtheBuzzwords tomorrow, Tuesday and Wednesday, June 8th and June 9th! Don’t miss it: https://t.co/B1JRaP4ZkE @apbspeakers @NdabaMandela @TutuNaomi #BLM #DEI https://t.co/OLT5XgzUxa",2021-06-07 13:02:29,Twitter for iPhone,5,...,5133,917,69500,2009-04-17 20:20:39,“Educating our boys teaches a community. Educating our girls raises a nation.”#TheAwakeningofMalcolmX • #XaNovel • #MalcolmLittle • #BettyBeforeX • #GrowingUpX,New York,1.0,NaN,1,1
2,3,1401946752652021762,https://twitter.com/ManletBrah/statuses/1401946752652021762,https://twitter.com/ManletBrah/statuses/1401946752652021762,ManletBrah,"*the army, intelligence agency, and nearly every corporation in America openly supports LGBT and BLM* wow in just a single moment we could be sent back to le dark ages 😪 https://t.co/6rONvY1YDy","*the army, intelligence agency, and nearly every corporation in America openly supports LGBT and BLM* wow in just a single moment we could be sent back to le dark ages 😪 https://t.co/6rONvY1YDy",2021-06-07 12:58:47,Twitter for Android,10,...,2039,456,1653,2021-05-21 07:01:39,God is good,NaN,NaN,NaN,1,0
3,4,1401946734373318657,https://twitter.com/filzaeeman/statuses/1401946734373318657,https://twitter.com/filzaeeman/statuses/1401946734373318657,filzaeeman,"Just like you don’t need to be black to speak about BLM, don’t need to be Palestinian to speak about Palestine, don’t need to be uyghur to speak about the Genocide in China, you don’t need to be Ahmadi to speak about us! This is about humanity and nothing else!","Just like you don’t need to be black to speak about BLM, don’t need to be Palestinian to speak about Palestine, don’t need to be uyghur to speak about the Genocide in China, you don’t need to be Ahmadi to speak about us! This is about humanity and nothing else!",2021-06-07 12:58:43,Twitter for iPhone,8,...,8082,452,1068,2013-01-06 19:33:36,All praise to the most high☝🏽,Tere ghar ke saamne,NaN,NaN,1,1
4,5,1401946551921041412,https://twitter.com/brawday/statuses/1401946551921041412,https://twitter.com/brawday/statuses/1401946551921041412,brawday,Tories told to \'take action\' after MP compares BLM to dictators and Nazi salutes https://t.co/7i1halIUbd,Tories told to \'take action\' after MP compares BLM to dictators and Nazi salutes https://t.co/7i1halIUbd,2021-06-07 12:57:59,Twitter Web App,3,...,132631,3856,8945,2013-07-10 03:48:31,🏴󠁧󠁢󠁳󠁣󠁴󠁿#standwithNicola Scottish never British Independence is normal Tory or #indyref2 That\'s all thats left,BONNIE SCOTLAND,NaN,NaN,1,1

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7500 entries, 0 to 2499
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       7500 non-null   int64
 1   tweetid                  7500 non-null   int64
 2   guid                     7500 non-null   object
 3   link                     7500 non-null   object
 4   author                   7500 non-null   object
 5   title                    7500 non-null   object
 6   description              7500 non-null   object
 7   pubdate                  7500 non-null   object
 8   source                   7500 non-null   object
 9   favorite_count           7500 non-null   int64
 10  retweet_count            7500 non-null   int64
 11  lang                     7500 non-null   object
 12  quoted_text              504 non-null    object
 13  tweet_type               7500 non-null   object
 14  in_reply_to_screen_name  3280 non-null   object
 15  in_reply_to_user_id      7500 non-null   int64
 16  in_reply_to_status_id    7500 non-null   int64
 17  retweeted_screen_name    2804 non-null   object
 18  retweeted_user_id        7500 non-null   int64
 19  retweeted_status_id      7500 non-null   int64
 20  user_id                  7500 non-null   int64
 21  profile_image_url        7500 non-null   object
 22  user_statuses_count      7500 non-null   int64
 23  user_friends_count       7500 non-null   int64
 24  user_followers_count     7500 non-null   int64
 25  user_created_at          7500 non-null   datetime64[ns]
 26  user_bio                 6458 non-null   object
 27  user_location            4797 non-null   object
 28  user_verified            118 non-null    float64
 29  Unnamed: 29              0 non-null      float64
 30  week                     7500 non-null   object
 31  class                    7500 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(13), object(16)
memory usage: 1.9+ MB

In [20]:
df['user_account_age'] = (pd.datetime.today() - df['user_created_at']).dt.days/365

<ipython-input-20-58b6c1d4d0b4>:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  df['user_account_age'] = (pd.datetime.today() - df['user_created_at']).dt.days/365

In [23]:
final = df[['tweetid','user_statuses_count','user_friends_count','user_followers_count','user_account_age','favorite_count','retweet_count','week','class']]

In [24]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7500 entries, 0 to 2499
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   tweetid               7500 non-null   int64
 1   user_statuses_count   7500 non-null   int64
 2   user_friends_count    7500 non-null   int64
 3   user_followers_count  7500 non-null   int64
 4   user_account_age      7500 non-null   float64
 5   favorite_count        7500 non-null   int64
 6   retweet_count         7500 non-null   int64
 7   week                  7500 non-null   object
 8   class                 7500 non-null   int64
dtypes: float64(1), int64(7), object(1)
memory usage: 585.9+ KB

In [25]:
final.head()

,tweetid,user_statuses_count,user_friends_count,user_followers_count,user_account_age,favorite_count,retweet_count,week,class
0,1401948148004687873,51125,439,6839,11.323288,3,0,1,0
1,1401947685964468230,5133,917,69500,12.405479,5,2,1,1
2,1401946752652021762,2039,456,1653,0.304110,10,0,1,0
3,1401946734373318657,8082,452,1068,8.679452,8,5,1,1
4,1401946551921041412,132631,3856,8945,8.172603,3,3,1,1

In [21]:
final.to_csv('dataframe.csv')

In [22]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   retweet_count  2500 non-null   int64
 1   class          2500 non-null   int64
dtypes: int64(2)
memory usage: 39.2 KB

In [23]:
df

,id,tweetid,guid,link,author,title,description,pubdate,source,favorite_count,...,user_friends_count,user_followers_count,user_created_at,user_bio,user_location,user_verified,Unnamed: 29,week,class,user_account_age
0,1,1401948148004687873,https://twitter.com/Lynn_GT/statuses/1401948148004687873,https://twitter.com/Lynn_GT/statuses/1401948148004687873,Lynn_GT,It’s going to be interesting to hear all those sports fans saying you shouldn’t bring politics into football (BLM - not that I think it’s political) squaring their approval of Johnson wading in on the cricket and Olly Robinson.,It’s going to be interesting to hear all those sports fans saying you shouldn’t bring politics into football (BLM - not that I think it’s political) squaring their approval of Johnson wading in on the cricket and Olly Robinson.,2021-06-07 13:04:20,Twitter for iPhone,3,...,439,6839,2010-05-17 16:38:35,"Lover of Entlebuchers, Italy and Amarone in equal parts! I no longer follow back automatically. #WokeAndProud",NaN,NaN,NaN,1,0,11.164384
1,2,1401947685964468230,https://twitter.com/ilyasahShabazz/statuses/1401947685964468230,https://twitter.com/ilyasahShabazz/statuses/1401947685964468230,ilyasahShabazz,"Looking forward to sharing my thoughts with this dynamic duo, on the Black Family panel, at #BeyondtheBuzzwords tomorrow, Tuesday and Wednesday, June 8th and June 9th! Don’t miss it: https://t.co/B1JRaP4ZkE @apbspeakers @NdabaMandela @TutuNaomi #BLM #DEI https://t.co/OLT5XgzUxa","Looking forward to sharing my thoughts with this dynamic duo, on the Black Family panel, at #BeyondtheBuzzwords tomorrow, Tuesday and Wednesday, June 8th and June 9th! Don’t miss it: https://t.co/B1JRaP4ZkE @apbspeakers @NdabaMandela @TutuNaomi #BLM #DEI https://t.co/OLT5XgzUxa",2021-06-07 13:02:29,Twitter for iPhone,5,...,917,69500,2009-04-17 20:20:39,“Educating our boys teaches a community. Educating our girls raises a nation.”#TheAwakeningofMalcolmX • #XaNovel • #MalcolmLittle • #BettyBeforeX • #GrowingUpX,New York,1.0,NaN,1,1,12.246575
2,3,1401946752652021762,https://twitter.com/ManletBrah/statuses/1401946752652021762,https://twitter.com/ManletBrah/statuses/1401946752652021762,ManletBrah,"*the army, intelligence agency, and nearly every corporation in America openly supports LGBT and BLM* wow in just a single moment we could be sent back to le dark ages 😪 https://t.co/6rONvY1YDy","*the army, intelligence agency, and nearly every corporation in America openly supports LGBT and BLM* wow in just a single moment we could be sent back to le dark ages 😪 https://t.co/6rONvY1YDy",2021-06-07 12:58:47,Twitter for Android,10,...,456,1653,2021-05-21 07:01:39,God is good,NaN,NaN,NaN,1,0,0.147945
3,4,1401946734373318657,https://twitter.com/filzaeeman/statuses/1401946734373318657,https://twitter.com/filzaeeman/statuses/1401946734373318657,filzaeeman,"Just like you don’t need to be black to speak about BLM, don’t need to be Palestinian to speak about Palestine, don’t need to be uyghur to speak about the Genocide in China, you don’t need to be Ahmadi to speak about us! This is about humanity and nothing else!","Just like you don’t need to be black to speak about BLM, don’t need to be Palestinian to speak about Palestine, don’t need to be uyghur to speak about the Genocide in China, you don’t need to be Ahmadi to speak about us! This is about humanity and nothing else!",2021-06-07 12:58:43,Twitter for iPhone,8,...,452,1068,2013-01-06 19:33:36,All praise to the most high☝🏽,Tere ghar ke saamne,NaN,NaN,1,1,8.520548
4,5,1401946551921041412,https://twitter.com/brawday/statuses/1401946551921041412,https://twitter.com/brawday/statuses/1401946551921041412,brawday,Tories told to \'take action\' after MP compares BLM to dictators and Nazi salutes https://t.co/7i1halIUbd,Tories told to \'take action\' after MP compares BLM to dictators and Nazi salutes https://t.co/7i1halIUbd,2021-06-07 12:57:59,Twitter Web App,3,...,3856,8945,2013-07-10 03:48:31,🏴󠁧󠁢󠁳󠁣󠁴󠁿#standwithNicola Scottish never British Independence is normal Tory or #indyref2 That\'s all thats left,BONNIE SCOTLAND,NaN,NaN,1,1,8.016438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,1412176145915813892,https://twitter.com/DoraHol97570423/statuses/1412176145915813892,https://twitter.com/DoraHol97570423/statuses/1412176145915813892,DoraHol97570423,RT @Jaxzon2008: A Bit of Black History #ONEV1 #BLM #wtpBLUE #OVFAF,A Bit of Black History #ONEV1 #BLM #wtpBLUE #OVFAF https://t.co/Rb2IrkaPRO,2021-07-05 18:26:44,Twitter for Android,0,...,508,249,2021-01-08 20:30:53,An American Woman of the World,NaN,NaN,NaN,3,1,0.509589
2496,2497,1412176133592961024,https://twitter.com/Politicatnmouse/statuses/1412176133592961024,https://twitter.com/Politicatnmouse/statuses/1412176133592961024,Politicatnmouse,RT @CatsCops: Wishing you all a great week!! This Saturday join us for a special event in the park!! #soupformyfamily #catsnotcops #catsnot…,Wishing you all a great week!! This Saturday join us for a special event in the park!! #soupformyfamily #catsnotcops #catsnotcopsdenver #denverprotests #blm #freedom #music #denver https://t.co/webskjSUKu,2021-07-05 18:26:41,Twitter Web App,0,...,1838,998,2012-04-22 19:11:50,"I want to live in a world where people evaluate their lives not by what they get out of it, but what they give during it. #notmeus",Stolen Land,NaN,NaN,3,1,9.230137
2497,2498,1412176071919771652,https://twitter.com/Jimmyng88785636/statuses/1412176071919771652,https://twitter.com/Jimmyng88785636/statuses/1412176071919771652,Jimmyng88785636,"@axios And the justic department continue ignore blm folks that attack innocent citizen, burnning the federal building, torch the business…. Oh no that is peacful protest…. What a shame","@axios And the justic department continue ignore blm folks that attack innocent citizen, burnning the federal building, torch the business…. Oh no that is peacful protest…. What a shame",2021-07-05 18:26:27,Twitter for iPhone,0,...,2,1,2019-08-17 00:55:29,NaN,NaN,NaN,NaN,3,0,1.909589
2498,2499,1412176049312501760,https://twitter.com/NadialloydTO/statuses/1412176049312501760,https://twitter.com/NadialloydTO/statuses/1412176049312501760,NadialloydTO,A proud mama just sent me this photo of her lovely son graduating and wearing my BLM mask! My heart is full. https://t.co/XtdoxdhTBt,A proud mama just sent me this photo of her lovely son graduating and wearing my BLM mask! My heart is full. https://t.co/XtdoxdhTBt,2021-07-05 18:26:21,Twitter for iPhone,108,...,2760,2239,2013-11-27 22:01:21,TORONTO: ARTIST / DESIGNER / MASK MAKER. As seen on the Toronto @Raptors & Mayor @JohnTory! Shop face masks and more at https://t.co/F586wXJciv,"Toronto, Ontario",NaN,NaN,3,0,7.630137
2499,2500,1412176041750245377,https://twitter.com/plerp4/statuses/1412176041750245377,https://twitter.com/plerp4/statuses/1412176041750245377,plerp4,"@ROMIMUSIC @Alan_sbg No, Kwame got mad at them for laughing about him being drafted #1. His whole YouTube channel is rants about “black on black crime”, claiming BLM is brainwashing the Black community, him being a Trump supporter, etc. His video on the Jacob Blake shooting: https://t.co/z3x8t5iZWc","@ROMIMUSIC @Alan_sbg No, Kwame got mad at them for laughing about him being drafted #1. His whole YouTube channel is rants about “black on black crime”, claiming BLM is brainwashing the Black community, him being a Trump supporter, etc. His video on the Jacob Blake shooting: https://t.co/z3x8t5iZWc",2021-07-05 18:26:19,Twitter Web App,0,...,0,2,2021-03-31 22:33:05,NaN,NaN,NaN,NaN,3,0,0.284932